set encoding=utf-8
set foldmethod=indent
set foldlevel=99
set number
set splitbelow
set splitright
set mouse=a
set numberwidth=1 "ancho de numeros
set clipboard=unnamed "permiter integracion del clipboard
syntax enable
set showcmd
set ruler
set showmatch
set sw=2 "spacios en lugar de tabs
set laststatus=2


so ~/.config/vim/plugins.vim
so ~/.config/vim/key-maps.vim



colorscheme gruvbox
set background=dark
let g:gruvbox_contrast_dark="hard"

"conf easymotion key
let NERDTreeQuitOnOpen=1

